### ISSUE TITLE
Building with Java 1.8 throws javadoc creation error

### ISSUE THREAD

**Issue by vikubel** [robotframework/jrobotremoteserver#30]
With Java 1.8, building using command :

```
mvn clean package assembly:single
```

throws following exceptions and fails:

``` Java
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:205)
[ERROR] at com.sun.tools.javadoc.Main.execute(Main.java:64)
[ERROR] at com.sun.tools.javadoc.Main.main(Main.java:54)
[ERROR] javadoc: error - java.lang.IllegalArgumentException
[ERROR]
[ERROR] Command line was: <somepath>\Java\jdk1.8.0_60\jre\..\bin\javadoc.exe -J-Dhttp.proxySet=true -J-Dhttp.proxyHost=foo.com -J-Dht
tp.proxyPort=nn "-J-Dhttp.nonProxyHosts=\"localhost|*.foo.com\"" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '<somepath>\jrobotremoteserver\target\apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Solution:
[Reference: ](http://stackoverflow.com/questions/24615547/cant-build-hadoop-2-4-1-with-java8)

Need to build using following command:

```
mvn  clean package assembly:single -Dmaven.javadoc.skip=true
```

**Comment by ombre42** [comment]
Thanks for reporting this. Eclipse added some of these Javadoc items. And sometimes I didn't feel like elaborating on them. Unfortunate that javadoc issues cause a build to fail instead of generating warnings. At least it is easy to fix :)
