### ISSUE TITLE
jrobotremoteserver 4.1.1 doesn't boot up with Spring Boot 3.2.2 

### ISSUE THREAD

**Issue by quarky42** [robotframework/jrobotremoteserver#72]
jrobotremoteserver 4.1.1 doesn't boot up with Spring Boot 3.2.2 
Eclipse Temurin Java 17.0.8.1

It worked with the older Spring Boot we were using.  Is there a compatibility issue with the new Spring Boot 3.2?

We had been using Spring Boot 2.7.3, prior.

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.2)

2024-02-09T23:25:18.165Z  INFO 1 --- [someAppName] [           main] o.somewhere.san.someAppNamemock.Application   : Starting Application v0.0.1 using Java 17.0.8.1 with PID 1
(/someAppName-mock.jar started by root in /)
2024-02-09T23:25:18.170Z  INFO 1 --- [someAppName] [           main] o.somewhere.san.someAppNamemock.Application   : The following 1 profile is active: "default"
2024-02-09T23:25:18.926Z  INFO 1 --- [someAppName] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT m
ode.
2024-02-09T23:25:18.939Z  INFO 1 --- [someAppName] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9 ms. Found 0 M
ongoDB repository interfaces.
2024-02-09T23:25:19.134Z  WARN 1 --- [someAppName] [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cance
lling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean
with name 'remoteServer' defined in class path resource [org/somewhere/san/someAppNamemock/AppConfiguration.class]: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory method 'remoteServer' threw exc
eption with message: javax/servlet/Servlet
2024-02-09T23:25:19.142Z  INFO 1 --- [someAppName] [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-02-09T23:25:19.159Z ERROR 1 --- [someAppName] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through constructor par
ameter 0: Error creating bean with name 'remoteServer' defined in class path resource [org/somewhere/san/someAppNamemock/AppConfiguration.class]: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory m
ethod 'remoteServer' threw exception with message: javax/servlet/Servlet
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-6.1
.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[spring-beans-6.1.
3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.1.3.jar!/
:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6
.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.3.jar!/:6.1
.3]
   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.3.jar!/:
6.1.3]
   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.3.jar!/:6.1.3]
   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar!/:3.2.2]
   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar!/:3.2.2]
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar!/:3.2.2]
   at o.somewhere.san.someAppNamemock.Application.main(Application.java:45) ~[!/:0.0.1]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
   at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
   at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[someAppName-mock.jar:0.0.1]
   at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[someAppName-mock.jar:0.0.1]
   at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[someAppName-mock.jar:0.0.1]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'remoteServer' defined in class path resource [org/somewhere/san/someAppNamemock/AppConfiguration.class]: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory method 'remoteServer' threw exception with message: javax/servlet/Servlet
   at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:639) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring
-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[spring-beans-6.1.
3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.1.3.jar!/
:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6
.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785) ~[spring-beans-6.1.3.jar!/:6.1.3]
   ... 23 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory method 'remoteServer' th
rew exception with message: javax/servlet/Servlet
   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:647) ~[spring-beans-6.1.3.jar!/:6.1.3]
   ... 37 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Servlet
   at o.somewhere.san.someAppNamemock.AppConfiguration.remoteServer(AppConfiguration.java:32) ~[!/:0.0.1]
   at o.somewhere.san.someAppNamemock.AppConfiguration$$SpringCGLIB$$0.CGLIB$remoteServer$0(<generated>) ~[!/:0.0.1]
   at o.somewhere.san.someAppNamemock.AppConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[!/:0.0.1]
   at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.3.jar!/:6.1.3]
   at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.1.3.jar
!/:6.1.3]
   at o.somewhere.san.someAppNamemock.AppConfiguration$$SpringCGLIB$$0.remoteServer(<generated>) ~[!/:0.0.1]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
   at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.3.jar!/:6.1.3]
   ... 38 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet
   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[na:na]
   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[na:na]
   at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:104) ~[someAppName-mock.jar:0.0.1]
   at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91) ~[someAppName-mock.jar:0.0.1]
   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
   ... 49 common frames omitted

2024-02-09T23:25:38.406Z  WARN 1 --- [someAppName] [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cance
lling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean
with name 'remoteServer' defined in class path resource [org/somewhere/san/someAppNamemock/AppConfiguration.class]: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory method 'remoteServer' threw exc
eption with message: javax/servlet/Servlet
2024-02-09T23:25:38.419Z  INFO 1 --- [someAppName] [           main] .s.b.a.l.ConditionEvaluationReportLogger :
san_someAppName-mock.1.haq44xnye07s@docker-desktop    |
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-02-09T23:25:38.445Z ERROR 1 --- [someAppName] [           main] o.s.boot.SpringApplication               : Application run failed
san_someAppName-mock.1.haq44xnye07s@docker-desktop    |
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through constructor par
ameter 0: Error creating bean with name 'remoteServer' defined in class path resource [org/somewhere/san/someAppNamemock/AppConfiguration.class]: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory m
ethod 'remoteServer' threw exception with message: javax/servlet/Servlet
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-6.1
.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[spring-beans-6.1.
3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.1.3.jar!/
:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6
.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.3.jar!/:6.1
.3]
   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.3.jar!/:
6.1.3]
   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.3.jar!/:6.1.3]
   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar!/:3.2.2]
   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar!/:3.2.2]
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar!/:3.2.2]
   at o.somewhere.san.someAppNamemock.Application.main(Application.java:45) ~[!/:0.0.1]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
   at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
   at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[someAppName-mock.jar:0.0.1]
   at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[someAppName-mock.jar:0.0.1]
   at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[someAppName-mock.jar:0.0.1]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'remoteServer' defined in class path resource [org/somewhere/san/someAppNamemock/AppConfiguration.class]: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory method 'remoteServer' threw exception with message: javax/servlet/Servlet
   at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:639) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring
-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[spring-beans-6.1.
3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.1.3.jar!/
:6.1.3]
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6
.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785) ~[spring-beans-6.1.3.jar!/:6.1.3]
   ... 23 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.robotframework.remoteserver.RemoteServer]: Factory method 'remoteServer' threw exception with message: javax/servlet/Servlet
   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177) ~[spring-beans-6.1.3.jar!/:6.1.3]
   at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:647) ~[spring-beans-6.1.3.jar!/:6.1.3]
   ... 37 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Servlet
   at o.somewhere.san.someAppNamemock.AppConfiguration.remoteServer(AppConfiguration.java:32) ~[!/:0.0.1]
   at o.somewhere.san.someAppNamemock.AppConfiguration$$SpringCGLIB$$0.CGLIB$remoteServer$0(<generated>) ~[!/:0.0.1]
   at o.somewhere.san.someAppNamemock.AppConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[!/:0.0.1]
   at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.3.jar!/:6.1.3]
   at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.1.3.jar
!/:6.1.3]
   at o.somewhere.san.someAppNamemock.AppConfiguration$$SpringCGLIB$$0.remoteServer(<generated>) ~[!/:0.0.1]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
   at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.3.jar!/:6.1.3]
   ... 38 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet
   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[na:na]
   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[na:na]
   at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:104) ~[someAppName-mock.jar:0.0.1]
   at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91) ~[someAppName-mock.jar:0.0.1]
   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
   ... 49 common frames omitted
```

**Comment by quarky42** [comment]
I did find that it does work with both 3.0.14 and 3.1.8.  I think the first time I tried 3.1.8, I had a secondary problem as well.
